services:
  - type: web
    name: navi-pro
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start -- -p 10000
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      - key: NEXT_PUBLIC_TEMPLATE
        value: corporate
